* $.couch.msie
jquery.couch.js depends on jquery 1.8.2. It checks $.couch.msie in its main
ajax call. Its enable the cache option is !$.couch.msie. I set it to always
true for now. If IE spits the dummy this is the cause maybe, and IE will have
to be detected.
http://stackoverflow.com/questions/14892095/browser-msie-error-after-update-to-jquery-1-9-1

TODO
* fix up package.json script property, should run docco(h)
* factor out jquery dependency, which means:
Extracting relevant jquery code , possibly using xmlhttprequest on node, 
Maybe use zeptojs.com for util function.
* session support for node version
  http://codetwizzle.com/articles/couchdb-cookie-authentication-nodejs-nano/
  https://www.npmjs.org/package/nano
* attachments
* batching requests?
 This object will internally keep track of revisions it's seen before and
 batches http requests that happen in the same "tick" to go out at the same time
 using CouchDB's batch processing APIs.
 https://github.com/creationix/couch-client
* incorporate reliable changes lib
https://github.com/iriscouch/follow
* streaming of attachments
See https://github.com/flatiron/cradle
